version: "3.9"
services:
  web:
    # restart: always
    build:
      args:
        - PORT=9000
        - TOKEN_SECRET=tokensecret
        # - DATABASE_URL=postgresql://postgres:postgres@db:5432/video-docker?schema=public
        - PGHOST=db
        - PGPORT=5432
        - PGUSER=postgres
        - PGPASSWORD=postgres
        - PGDATABASE=video-docker
        - NATS_SERVER_URL=nats:4222
      context: .
    environment:
      - NODE_ENV=DEV

    ports:
      - "9000:9000"
    depends_on:
      - db
      - nats
    command: ["./start.sh"]
    links:
      - db
      - nats

  db:
    image: postgres:14.1-alpine
    # restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: video-docker
    ports:
      - "5432:5432"
    # volumes:
    #   - db:/var/lib/postgresql/data
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
