version: "3.9"
services:
  web:
    # restart: always
    build:
      args:
        - PORT=9000
        - TOKEN_SECRET=tokensecret
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/videoapp?schema=public
      context: .
    environment:
      - NODE_ENV=PROD

    ports:
      - "9000:9000"
    depends_on:
      - db
    command: ["./start.sh"]
    links:
      - db

  # db:
  #   image: postgres:14.1-alpine
  #   # restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: videoapp
  #   ports:
  #     - "5432:5432"
    # volumes:
    #   - db:/var/lib/postgresql/data
